- hosts: kube_control_plane[0]
  tasks:
    - name: Install ArgoCD
      shell: |
        kubectl create namespace argocd || true
        kubectl apply -n argocd \
          -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
